/**
 * models/room.model.ts
 *
 * Mongoose model for an interview room.
 *
 * Lifecycle:
 *  scheduled → active (interviewer calls /start)
 *             → completed (interviewer calls /end)
 *             → cancelled (interviewer / admin cancels before it starts)
 *
 * A room has a unique `roomId` (UUID) used in Socket.IO as the channel name,
 * and an optional `inviteToken` (JWT) sent to the candidate via email so they
 * can join without prior registration.
 */
const mongoose = require("mongoose");
const crypto = require("crypto");
const interviewRoomSchema = new mongoose.Schema({
    // UUID generated by default; also used as the real-time room channel name
    roomId: { type: String, unique: true, index: true, default: () => crypto.randomUUID() },
    title: { type: String, required: true },
    description: { type: String },
    // Populated references to User documents
    interviewer: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    candidate: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    scheduledAt: { type: Date, required: true },
    durationMinutes: { type: Number, default: 60 },
    status: {
        type: String,
        enum: ['scheduled', 'active', 'completed', 'cancelled'],
        default: 'scheduled',
    },
    mode: {
        type: String,
        enum: ['live', 'take_home'],
        default: 'live',
    },
    // Invite link mechanics
    inviteToken: { type: String },
    inviteExpiresAt: { type: Date },
    problemStatement: { type: String },
    questionId: { type: mongoose.Schema.Types.ObjectId, ref: 'Question' },
    techStack: [{ type: String }],
    difficultyLevel: {
        type: String,
        enum: ['easy', 'medium', 'hard'],
        default: 'medium',
    },
    whiteboardKey: {
        type: String,
        default: () => crypto.randomBytes(32).toString('hex'),
    },
}, {
    timestamps: true,
});
interviewRoomSchema.index({ interviewer: 1, createdAt: -1 });
exports.InterviewRoom = mongoose.model('InterviewRoom', interviewRoomSchema);
