"use strict";
/**
 * models/room.model.ts
 *
 * Mongoose model for an interview room.
 *
 * Lifecycle:
 *  scheduled → active (interviewer calls /start)
 *             → completed (interviewer calls /end)
 *             → cancelled (interviewer / admin cancels before it starts)
 *
 * A room has a unique `roomId` (UUID) used in Socket.IO as the channel name,
 * and an optional `inviteToken` (JWT) sent to the candidate via email so they
 * can join without prior registration.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.InterviewRoom = void 0;
const mongoose_1 = __importStar(require("mongoose"));
const crypto_1 = __importDefault(require("crypto"));
const interviewRoomSchema = new mongoose_1.Schema({
    // UUID generated by default; also used as the real-time room channel name
    roomId: { type: String, unique: true, index: true, default: () => crypto_1.default.randomUUID() },
    title: { type: String, required: true },
    description: { type: String },
    organization: { type: mongoose_1.Schema.Types.ObjectId, ref: 'Organization', index: true },
    // Populated references to User documents
    interviewer: { type: mongoose_1.Schema.Types.ObjectId, ref: 'User', required: true },
    candidate: { type: mongoose_1.Schema.Types.ObjectId, ref: 'User' },
    scheduledAt: { type: Date, required: true },
    durationMinutes: { type: Number, default: 60 },
    status: {
        type: String,
        enum: ['scheduled', 'active', 'completed', 'cancelled'],
        default: 'scheduled',
    },
    mode: {
        type: String,
        enum: ['live', 'take_home'],
        default: 'live',
    },
    // Invite link mechanics
    inviteToken: { type: String },
    inviteExpiresAt: { type: Date },
    problemStatement: { type: String },
    questionId: { type: mongoose_1.Schema.Types.ObjectId, ref: 'Question' },
    techStack: [{ type: String }],
    difficultyLevel: {
        type: String,
        enum: ['easy', 'medium', 'hard'],
        default: 'medium',
    },
    whiteboardKey: {
        type: String,
        default: () => crypto_1.default.randomBytes(32).toString('hex'),
    },
}, {
    timestamps: true,
});
interviewRoomSchema.index({ interviewer: 1, createdAt: -1 });
interviewRoomSchema.index({ organization: 1, scheduledAt: -1 });
exports.InterviewRoom = mongoose_1.default.model('InterviewRoom', interviewRoomSchema);
