/**
 * models/room.model.ts
 *
 * Mongoose model for an interview room.
 *
 * Lifecycle:
 *  scheduled → active (interviewer calls /start)
 *             → completed (interviewer calls /end)
 *             → cancelled (interviewer / admin cancels before it starts)
 *
 * A room has a unique `roomId` (UUID) used in Socket.IO as the channel name,
 * and an optional `inviteToken` (JWT) sent to the candidate via email so they
 * can join without prior registration.
 */

import mongoose, { Schema, Document } from 'mongoose';
import crypto from 'crypto';
import { IUser } from './user.model';

export interface IInterviewRoom extends Document {
  roomId: string;                                  // UUID used as the Socket.IO room name
  title: string;
  description?: string;
  interviewer: mongoose.Types.ObjectId | IUser;    // the person conducting the interview
  candidate?: mongoose.Types.ObjectId | IUser;     // populated when candidate is known
  scheduledAt: Date;
  durationMinutes: number;
  status: 'scheduled' | 'active' | 'completed' | 'cancelled';
  inviteToken?: string;                            // JWT sent to candidate; expires after the session
  inviteExpiresAt?: Date;
  problemStatement?: string;                       // markdown description of the challenge
  techStack?: string[];                            // e.g. ['TypeScript', 'React']
  difficultyLevel: 'easy' | 'medium' | 'hard';
  createdAt: Date;
  updatedAt: Date;
}

const interviewRoomSchema = new Schema<IInterviewRoom>(
  {
    // UUID generated by default; also used as the real-time room channel name
    roomId: { type: String, unique: true, index: true, default: () => crypto.randomUUID() },
    title:  { type: String, required: true },
    description: { type: String },

    // Populated references to User documents
    interviewer: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    candidate:   { type: Schema.Types.ObjectId, ref: 'User' },

    scheduledAt:     { type: Date, required: true },
    durationMinutes: { type: Number, default: 60 },

    status: {
      type: String,
      enum: ['scheduled', 'active', 'completed', 'cancelled'],
      default: 'scheduled',
    },

    // Invite link mechanics
    inviteToken:     { type: String },
    inviteExpiresAt: { type: Date },

    problemStatement: { type: String },
    techStack: [{ type: String }],
    difficultyLevel: {
      type: String,
      enum: ['easy', 'medium', 'hard'],
      default: 'medium',
    },
  },
  {
    timestamps: true,
  }
);

export const InterviewRoom = mongoose.model<IInterviewRoom>(
  'InterviewRoom',
  interviewRoomSchema
);
